services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Chicago
    volumes:
      - /home/media/prowlarr:/config:z
      - /var/data:/data:z
    ports:
      - 9696:9696
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Chicago
    volumes:
      - /home/media/radarr:/config:z
      - /var/data:/data:z
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Chicago
    volumes:
      - /home/media/sonarr:/config:z
      - /var/data:/data:z
    ports:
      - 8989:8989
    restart: unless-stopped
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Chicago
    volumes:
      - /home/media/readarr:/config:z
      - /var/data:/data:z
    ports:
      - 8787:8787
    restart: unless-stopped
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Chicago
    volumes:
      - /home/media/lidarr:/config:z
      - /var/data:/data:z
    ports:
      - 8686:8686
    restart: unless-stopped
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Chicago
      - VERSION=docker
      - PLEX_CLAIM=
    volumes:
      - /home/media/plex:/config:z
      - /var/data:/data:z
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Chicago
      - WEBUI_PORT=8080
      - TORRENTING_PORT=16686
    volumes:
      - /home/media/qbittorrent:/config:z
      - /var/data:/data:z
    ports:
      - 8080:8080
      - 16686:16686
      - 16686:16686/udp
    restart: unless-stopped
  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Chicago
    volumes:
      - /home/media/ombi:/config:z
    ports:
      - 3579:3579
    restart: unless-stopped
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Chicago
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=ombi
      - MYSQL_USER=ombi
      - MYSQL_PASSWORD=ombi
    volumes:
      - /home/media/mariadb:/config:z
    ports:
      - 3306:3306
    restart: unless-stopped
  unpackerr:
    image: golift/unpackerr
    container_name: unpackerr
    volumes:
      - /var/data:/data:z
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Chicago
      - UN_LOG_FILE=/data/unpackerr.log
      - UN_SONARR_0_URL=
      - UN_SONARR_0_API_KEY=
      - UN_RADARR_0_URL=
      - UN_RADARR_0_API_KEY=
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/Chicago
    volumes:
      - /home/media/kavita:/config:z
      - /var/data:/data:z
    ports:
      - 5000:5000
    restart: unless-stopped
